apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mongo-serviceaccount.yaml
- mongo-cluster.yaml

# TODO: generate a random password
secretGenerator:
  - name: fights-user-mongodb-password
    literals:
      - password=password
  - name: admin-mongodb-password
    literals:
      - password=password

generatorOptions:
    disableNameSuffixHash: true
