apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: quarkus-superheroes
roleRef:
  kind: Role
  name: default-role
  apiGroup: rbac.authorization.k8s.io