---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-apiserver
  namespace: ${argocd_namespace}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/apiserver/${kustomize_path}
    repoURL: https://github.com/joshgav/devenv.git
    targetRevision: main
    kustomize: {}
  syncPolicy:
    automated: {}
    syncOptions:
      - "RespectIgnoreDifferences=true"
  info: []
  ignoreDifferences:
    - group: apps/v1
      kind: Deployment
      name: spring-apiserver
      jqPathExpressions:
        - '.spec.template.spec.containers[].image'
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-app