apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-openshift-default.yaml
- cert-openshift-apiserver.yaml
# patchesStrategicMerge:
# - ingresscontroller_patch.yaml
# - issuer-acme_patch.yaml