---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: openshift-gitops-operator
spec:
    name: openshift-gitops-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    channel: latest
    installPlanApproval: Automatic