---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: eap
    namespace: openshift-operators
spec:
    name: eap
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    channel: stable
    installPlanApproval: Automatic