apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: broker-to-receiver
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventreceiver