apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: spring-apiserver
  labels:
    app: spring-apiserver
    app.kubernetes.io/component: build-config
    app.kubernetes.io/instance: spring-apiserver
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'spring-apiserver:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: spring-apiserver
        name: 's2i-openjdk-17:latest'
  source:
    type: Git
    git:
      uri: 'https://github.com/joshgav/spring-apiserver.git'
      ref: main
  triggers:
    - type: GitHub
      github:
        secret: l-qmx1ae2UvWU3HHeYXf
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
