# https://docs.openshift.com/container-platform/4.6/security/certificates/replacing-default-ingress-certificate.html
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apiserver-tls-certificate
spec:
  commonName: apiserver.ipi.aws.joshgav.com
  dnsNames:
    - apiserver.ipi.aws.joshgav.com
  secretName: apiserver-tls-keypair
  issuerRef:
    name: ca
    # name: acme
    kind: ClusterIssuer
    group: cert-manager.io
  subject:
    organizationalUnits:
      - 'kubernetes'
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
    - signing
