apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-apiserver
  labels:
    app: spring-apiserver
    app.kubernetes.io/component: spring-apiserver
    app.kubernetes.io/instance: spring-apiserver
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "spring-apiserver:latest"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: spring-apiserver
  template:
    metadata:
      labels:
        app.kubernetes.io/component: spring-apiserver
    spec:
      containers:
        - name: spring-apiserver
          image: spring-apiserver:latest
          imagePullPolicy: Always
          envFrom:
            - prefix: PG_
              secretRef:
                name: apiserver-dbcluster-pguser-apiserver
          env:
            - name: HOME
              value: /opt/jboss
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - containerPort: 9779
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/config
              name: app-properties
      volumes:
        - name: app-properties
          configMap:
            name: spring-apiserver-app-properties
            optional: true
