apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  extraConfig:
    # allows admins to generate API keys
    accounts.admin: apiKey
  controller:
    appSync: 60s
  ha:
    enabled: false
  monitoring:
    enabled: true
  rbac:
    defaultPolicy: "read-only"
    policy: "g, system:cluster-admins, role:admin\n"
    scopes: "[groups]"
  server:
    route:
      enabled: true
      tls:
        termination: reencrypt
        insecureEdgeTerminationPolicy: Redirect
  sso:
    provider: dex
    dex:
      openShiftOAuth: true