apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: noobaa-default-bucket-class
  namespace: noobaa
  labels:
    app: noobaa
spec:
  placementPolicy:
    tiers:
    - backingStores:
      - noobaa-pv
      placement: Spread