apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: event-statistics
spec:
  to:
    kind: Service
    name: event-statistics
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None