apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-tenant
resources:
- namespace.yaml
- minio-tenant-config-secret.yaml
- minio-root-creds-secret.yaml
- minio-user-secret.yaml
- tenant.yaml