---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: minio-operator
spec:
    name: minio-operator
    source: certified-operators
    sourceNamespace: openshift-marketplace
    channel: stable
    installPlanApproval: Automatic