# https://github.com/minio/operator/blob/master/docs/tenant_crd.adoc
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: tenant-1
  labels:
    app: minio
spec:
  serviceAccountName: default
  credsSecret:
    name: minio-root-creds
  users:
    - name: minio-tenant
  configuration:
    name: minio-tenant-config
  requestAutoCert: true
  features:
    bucketDNS: false
    domains: {}
  podManagementPolicy: Parallel
  buckets:
    - name: loki-data
  pools:
    - name: pool-0
      servers: 4
      volumesPerServer: 4
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true