apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-opentelemetry-operator
resources:
- namespace.yaml
- operatorgroup.yaml
- subscription.yaml
- generate-processors-rbac.yaml