apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: user1
  labels:
    strimzi.io/cluster: cluster1
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # consumer ACLs
      - resource:
          type: topic
          name: topic1
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: topic1
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: group1
          patternType: literal
        operation: Read
        host: "*"
      # producer ACLs
      - resource:
          type: topic
          name: topic1
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: topic1
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: topic1
          patternType: literal
        operation: Describe
        host: "*"