---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: rh-service-binding-operator
spec:
    name: rh-service-binding-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    channel: stable
    installPlanApproval: Automatic