apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  controller: {}
  dex:
    openShiftOAuth: true
  ha:
    enabled: false
  rbac: {}
  redis: {}
  repo: {}
  server:
    route:
      enabled: true
      tls:
        termination: reencrypt
        insecureEdgeTerminationPolicy: Redirect
