app:
  baseUrl: https://${bs_app_name}-backstage-backstage.${openshift_ingress_domain}/
backend:
  baseUrl: https://${bs_app_name}-backstage-backstage.${openshift_ingress_domain}/
  database:
    client: pg
    connection:
      # config options: https://node-postgres.com/apis/client
      host: ${bs_app_name}-backstage-pgcluster-rw
      port: 5432
      user: ${username}
      password: ${password}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      ssl:
        ca: # if you have a CA file and want to verify it you can uncomment this section
          $file: /var/run/secrets/backstage-pgcluster-ca

# Overrides the default catalog, which contains examples
# catalog:
#   # See https://backstage.io/docs/features/software-catalog/software-catalog-overview#adding-components-to-the-catalog for more details
#   # on how to get entities into the catalog.
#   locations: []
