apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gitlab
spec:
  to:
    kind: Service
    name: gitlab-webservice-default
    weight: 100
  port:
    targetPort: http-workhorse
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect