# see https://github.com/openshift/cert-manager-operator/blob/master/bindata/cert-manager-deployment/controller/cert-manager-deployment.yaml
apiVersion: operator.openshift.io/v1alpha1
kind: CertManager
metadata:
  # must be named cluster for operator-managed instance
  name: cluster
spec:
  managementState: "Managed"
  # see https://github.com/openshift/cert-manager-operator#using-unsupported-config-overrides-options
  unsupportedConfigOverrides:
    controller:
      args:
        - "--v=2"
        - "--cluster-resource-namespace=cert-manager"
        - "--leader-election-namespace=kube-system"
        - "--dns01-recursive-nameservers=8.8.8.8:53,8.8.4.4:53"
        - "--dns01-recursive-nameservers-only"