apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-apiserver
spec:
  template:
    spec:
      containers:
        - name: spring-apiserver
          envFrom:
            - prefix: KEYCLOAK_
              secretRef:
                name: keycloak-client-secret-spring-apiserver
            - prefix: PG_
              secretRef:
                name: apiserver-dbcluster-superuser
          env:
            - name: KEYCLOAK_ISSUER_URI
              value: https://keycloak-keycloak.apps.ipi.aws.joshgav.com/auth/realms/main